apiVersion: v1
kind: Namespace
metadata:
  name: route-ns
---

apiVersion: v1
kind: Namespace
metadata:
  name: gateway-ns
---

apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: gwctl
  namespace: gateway-ns
spec:
  controllerName: my-app/my-gateway-controller
---

apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: foo-gateway
  namespace: gateway-ns
spec:
  gatewayClassName: my-gateway-controller
  listeners:
  - name: prod-web
    port: 8080
    protocol: HTTP
    allowedRoutes:
      kinds:
      - kind: HTTPRoute
      namespaces:
        from: Selector
        selector:
          matchLabels:
            # This label is added automatically as of K8s 1.22
            # to all namespaces
            expose-apps: "true"


---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: my-route
  namespace: route-ns
  labels:
    expose-apps: "true"

spec:
  parentRefs:
  - kind: Gateway
    name: foo-gateway
    namespace: gateway-ns
  rules:
  - backendRefs:
    - name: nginx-service
      port: 8080


