apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    expose-apps: "true"
spec:
  selector:
    app: nginx-pod
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: nginx-port
      nodePort: 31111
