 apiVersion: v1
 kind: PersistentVolume
 metadata:
   name: mc-data-pv
 spec:
   capacity:
     storage: 2Gi
   # volumeType: local
   accessModes:
     - ReadWriteOnce
   storageClassName: manual
   hostPath:
     path: "/tmp/data"
#   claimRef:
#     name: mc-data-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-data-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeName: mc-data-pv
  
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
